[package]
name = "bananas_server"
version = "1.0.0"
edition = "2021"

[workspace]

[dependencies]
byteorder = "1"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
